#!/usr/bin/env python

import pexpect

child = pexpect.spawn("./ex19")
child.logfile = open("/home/pjd/src/lcthw/ex19log", "wb")
child.expect("\n>")
child.sendline("l")
child.expect("\n>")
child.sendline("n")
child.expect("\n>")
child.sendline("e")
child.expect("\n>")
child.sendline("w")
child.expect("\n>")
child.sendline("w")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("e")
child.expect("\n>")
child.sendline("n")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("a")
child.expect("\n>")
child.sendline("w")
child.expect("\n>")
child.sendline("s")
child.expect("\n>")
